version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: property_backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app
      - ./backend/property_listings.db:/app/property_listings.db
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: property_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
